apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  application.properties: |-
    greeting=Hello World
{{- range $key, $val := .Values.configmap }}
{{ $key | indent 4}}={{ $val }}
{{- end}}
